# Generated by Django 5.2.6 on 2025-09-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('episode_id', models.PositiveIntegerField(verbose_name='ID do Episódio')),
                ('opening_crawl', models.TextField(verbose_name='Texto de Abertura')),
                ('director', models.CharField(max_length=100, verbose_name='Diretor')),
                ('producer', models.CharField(max_length=200, verbose_name='Produtor')),
                ('release_date', models.DateField(verbose_name='Data de Lançamento')),
                ('created', models.DateTimeField(verbose_name='Criado em')),
                ('edited', models.DateTimeField(verbose_name='Editado em')),
                ('url', models.URLField(max_length=255, unique=True, verbose_name='URL da API')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['episode_id'],
            },
        ),
    ]
